name: smart_pantry
description: "Una aplicaci贸n para gesti贸n de inventario de alimentos y planificaci贸n de comidas."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Notificaciones y tareas en background
  flutter_local_notifications: ^19.2.1
  firebase_messaging: ^15.1.5
  workmanager: ^0.6.0
  permission_handler: ^12.0.0+1  # ACTUALIZADO: Ya existe, asegurar versi贸n correcta
  
  # Existing dependencies
  path_provider: ^2.0.0 
  google_generative_ai: ^0.4.7
  mobile_scanner: ^7.0.0
  camera: ^0.11.1
  google_ml_kit: ^0.20.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  sqflite: ^2.3.0
  flutter_dotenv: ^5.1.0
  image: ^4.1.3
  
  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  
  # Utilities
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  uuid: ^4.5.1
  image_picker: ^1.0.4
  cloudinary_public: ^0.23.1
  flutter_markdown: ^0.7.7+1
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/LOGOS/icono_app_zanahoria.png
    - assets/LOGOS/icono_app_Texto.png
    - .env
    - assets/avatars/